[SMAGENT-1583] Use probe builder container in jenkins (#1377)

diff --git a/scripts/jenkins/agent-build-presubmit/install-probe-and-run-system-test b/scripts/jenkins/agent-build-presubmit/install-probe-and-run-system-test
--- a/scripts/jenkins/agent-build-presubmit/install-probe-and-run-system-test
+++ b/scripts/jenkins/agent-build-presubmit/install-probe-and-run-system-test
@@ -10,30 +10,27 @@ SOURCE=$WORKSPACE
 INSTALL_DIR=$WORKSPACE/install
 OUT=$WORKSPACE/out
 BUILD=$WORKSPACE/build
-DRIVER_BUILD=$WORKSPACE/driver
 
-# The package build will create the different packages (.deb and .rpm). Also,
-# this builds and installs the package to allow dkms to build the driver.
-docker run -i --rm -e MAKE_JOBS=$(nproc) -v $SOURCE:/draios:ro -v $INSTALL_DIR:/opt/draios -v $OUT:/out -v /var/run/docker.sock:/var/run/docker.sock -v $BUILD:/code/agent/build quay.io/sysdig/agent-builder package
-rc=$?; if [[ $rc != 0 ]]; then echo "FAILED! Package build unsuccessful!";exit $rc; fi
-# This will generate the dragent container
-docker run -i --rm -e MAKE_JOBS=$(nproc) -v $SOURCE:/draios:ro -v $INSTALL_DIR:/opt/draios -v $OUT:/out -v /var/run/docker.sock:/var/run/docker.sock -v $BUILD:/code/agent/build quay.io/sysdig/agent-builder container
-rc=$?; if [[ $rc != 0 ]]; then echo "FAILED! Container build unsuccessful!";exit $rc; fi
-# This will install all of the tests to the install dir.
+# Run "install-test" to copy the system tests (and everything else) to
+# the install directory
 docker run -i --rm -e MAKE_JOBS=$(nproc) -v $SOURCE:/draios:ro -v $INSTALL_DIR:/opt/draios -v $OUT:/out -v /var/run/docker.sock:/var/run/docker.sock -v $BUILD:/code/agent/build quay.io/sysdig/agent-builder install-test
-rc=$?; if [[ $rc != 0 ]]; then echo "FAILED! Install-Test build unsuccessful!";exit $rc; fi
+rc=$?; if [[ $rc != 0 ]]; then echo "FAILED! Install-test unsuccessful!";exit $rc; fi
 
-docker run -i --rm -v $OUT:/out busybox chown -R `id -u`:`id -g` /out
-
-# Add the probe
-sudo apt-get install -y dkms
-sudo dpkg -i $OUT/draios-0.1.1dev-x86_64-agent.deb
-sudo /etc/init.d/dragent stop
-sudo insmod /lib/modules/$(uname -r)/updates/dkms/sysdigcloud-probe.ko
-
-sudo $SCRIPTS_DIR/../run-tests $INSTALL_DIR
-rc=$?; if [[ $rc != 0 ]]; then echo "FAILED! System Tests unsuccessful!";exit $rc; fi
-
-
-# Remove the probe
+# Just in case... remove the probe
 sudo rmmod sysdigcloud-probe
+
+# Build and insmod the kernel module
+docker pull sysdig/agent-kmodule:dev
+docker run -i --privileged --rm --name sysdig-agent-kmodule -v /usr:/host/usr:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro sysdig/agent-kmodule:dev
+rc=$?; if [[ $rc != 0 ]]; then echo "FAILED! Build agent-kmodule unsuccessful!";exit $rc; fi
+
+# Run the tests
+sudo $SCRIPTS_DIR/../run-tests $INSTALL_DIR
+rc=$?;
+if [[ $rc != 0 ]]; then
+    echo "FAILED! System Tests unsuccessful!";
+    # don't exit
+fi
+
+sudo rmmod sysdigcloud-probe
+exit $rc;
diff --git a/scripts/jenkins/run-tests b/scripts/jenkins/run-tests
--- a/scripts/jenkins/run-tests
+++ b/scripts/jenkins/run-tests
@@ -17,22 +17,40 @@ set +e
 unshare -m /bin/bash -c "$SETUP_CMD && cd /opt/draios/test && ./tests $@" 2>&1 | tee $TESTS_LOG
 set -e
 
+# Check for the indication that all tests were successful. This helps if there
+# is a seg fault or some other reason the test did not finish running.
+AT_LEAST_ONE_TEST_PASSED=$(grep -F "[  PASSED  ]" $TESTS_LOG)
+# Get a list of all tests that failed.
 FAILED_TESTS=$(awk '/ FAILED / && test_list==1 { print $4 } / FAILED.*listed below:/ { test_list=1 }' < $TESTS_LOG | tr \\n :)
 rm -f $TESTS_LOG
+
+if [ -z "$AT_LEAST_ONE_TEST_PASSED" ]
+then
+    echo "Test did not finish executing"
+    exit 1
+fi
 
 if [ -n "$FAILED_TESTS" ]
 then
 	echo "Some tests failed... restarting"
 	TESTS_LOG=`mktemp /tmp/tests.log.XXXXXX`
 	unshare -m /bin/bash -c "$SETUP_CMD && cd /opt/draios/test && ./tests --gtest_filter=$FAILED_TESTS" 2>&1 | tee $TESTS_LOG
+	AT_LEAST_ONE_TEST_PASSED=$(grep -F "[  PASSED  ]" $TESTS_LOG)
 	FAILED_TESTS=$(awk '/ FAILED / && test_list==1 { print $4 } / FAILED.*listed below:/ { test_list=1 }' < $TESTS_LOG | tr \\n :)
 	rm -f $TESTS_LOG
 
+	if [ -z "$AT_LEAST_ONE_TEST_PASSED" ]
+	then
+		echo "Tests did not finish executing on rerun, returning failure"
+		exit 1
+	fi
+
 	if [ -n "$FAILED_TESTS" ]
 	then
-		echo "Tests failed again, returning failure"
+		echo "At least one test failed twice, returning failure"
 		exit 1
 	fi
 fi
 
+echo "Tests passed"
 exit 0
