Add options for specifying exact agent image to use

diff --git a/scripts/install-agent-kubernetes b/scripts/install-agent-kubernetes
--- a/scripts/install-agent-kubernetes
+++ b/scripts/install-agent-kubernetes
@@ -229,7 +229,7 @@ function install_k8s_agent {
 	if [ $INSTALL_IMAGE_ANALYZER -eq 1 ] || [ $INSTALL_NODE_ANALYZER -eq 1 ]; then
 		# Image Analyzer config map
 		IA_CONFIG_FILE=$WORKDIR/sysdig-image-analyzer-configmap.yaml
-		
+
 		# If the collector was changed but the analysis manager was not this was
 		# most likely an onprem install, add the default analysis manager for that onprem
 		if [ ! -z "$API_ENDPOINT" ] && [ -z "$ANALYSIS_MANAGER" ]; then
@@ -303,15 +303,15 @@ function install_k8s_agent {
 		kubectl apply -f $HA_CONFIG_FILE --namespace=$NAMESPACE
 	fi
 
-	AGENT_STRING="agent"
 	if [ ! -z "$AGENT_SLIM" ]; then
 		DAEMONSET_FILE="$WORKDIR/sysdig-agent-slim-daemonset-v2.yaml"
-		AGENT_STRING="agent-slim"
+                sed -i.bak -e "s|\( *image: \).*/sysdig/agent-slim$|\1${REGISTRY}/${AGENT_SLIM_REPOSITORY}:${AGENT_VERSION}|" $DAEMONSET_FILE
+                sed -i.bak -e "s|\( *image: \).*/sysdig/agent-kmodule$|\1${REGISTRY}/${AGENT_KMOD_REPOSITORY}:${AGENT_VERSION}|" $DAEMONSET_FILE
 	else
 		DAEMONSET_FILE="$WORKDIR/sysdig-agent-daemonset-v2.yaml"
+                sed -i.bak -e "s|\( *image: \).*/sysdig/agent$|\1${REGISTRY}/${AGENT_REPOSITORY}:${AGENT_VERSION}|" $DAEMONSET_FILE
 	fi
 
-	sed -i.bak -e "s| *image: .*/sysdig/${AGENT_STRING}$|&:${AGENT_VERSION}|" $DAEMONSET_FILE
 
 	# Test for COS (Container-Optimized OS from Google)
 	# Enable EBPF if so.
@@ -341,7 +341,7 @@ function install_k8s_agent {
 			sed -i.bak -e "s|#  name: osrel|  name: osrel|" $DAEMONSET_FILE
 		fi
 	fi
-	
+
 	echo "* Deploying the sysdig agent"
 	kubectl apply -f $DAEMONSET_FILE --namespace=$NAMESPACE
 	sleep 5 # So we gave some time to create the pods and show something meaningful in the next command
@@ -390,7 +390,7 @@ function install_k8s_agent {
 
 			IA_MATCH="Add custom volume here"
 			IA_INSERT_VOLUME="      - name: custom-volume${NL}        hostPath:${NL}          path: ${IA_CUSTOM_PATH}"
-			
+
 			sed -i.bak -e "s|${IA_MATCH}|${IA_MATCH}${NL}${IA_INSERT_VOLUME}|" $NA_FILE
 
 			IA_MATCH="Add custom volume mount here"
@@ -474,6 +474,10 @@ REMOVE_AGENT=0
 OPENSHIFT=0
 INSTALL_IMAGE_ANALYZER=0
 INSTALL_NODE_ANALYZER=0
+REGISTRY="quay.io"
+AGENT_REPOSITORY="sysdig/agent"
+AGENT_SLIM_REPOSITORY="sysdig/agent-slim"
+AGENT_KMOD_REPOSITORY="sysdig/agent-kmodule"
 AGENT_VERSION="latest"
 WORKDIR=""
 
@@ -551,6 +555,42 @@ do
 				ADDITIONAL_CONF="${2}"
 			else
 				echo "ERROR: no value provided for additional conf option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
+		-ar|--agent_registry)
+			if is_valid_value "${2}"; then
+				REGISTRY="${2}"
+			else
+				echo "ERROR: no value provided for agent registry option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
+		-arr|--agent_repository)
+			if is_valid_value "${2}"; then
+				AGENT_REPOSITORY="${2}"
+			else
+				echo "ERROR: no value provided for agent repository option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
+		-asr|--agent_slim_repository)
+			if is_valid_value "${2}"; then
+				AGENT_SLIM_REPOSITORY="${2}"
+			else
+				echo "ERROR: no value provided for agent slim repository option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
+		-akr|--agent_kmod_repository)
+			if is_valid_value "${2}"; then
+				AGENT_KMOD_REPOSITORY="${2}"
+			else
+				echo "ERROR: no value provided for agent kmodule repository option, use -h | --help for $(basename ${0}) Usage"
 				exit 1
 			fi
 			shift
