Image analyzer scripts (#1959)
* Image Analyzer installation

* Image Analyzer config map managed

* Image Analyzer config map managed

* Image Analyzer installation

* Image Analyzer installation: custom volume

* Image Analyzer install script: fix new line on Mac

* help improved

* Image Analyzer yaml scripts downloaded from branch

* Image Analyzer installation is optional

* Image Analyzer help fixed

* install script improved

* commented lines removed and minor fix

* image analyzer yaml file renamed

* remove bogus file

Co-authored-by: Mattia Pagnozzi <mattia.pagnozzi@gmail.com>

diff --git a/scripts/install-agent-kubernetes b/scripts/install-agent-kubernetes
--- a/scripts/install-agent-kubernetes
+++ b/scripts/install-agent-kubernetes
@@ -34,6 +34,12 @@ function download_yamls {
 	curl -s -o $WORKDIR/sysdig-agent-daemonset-v2.yaml https://raw.githubusercontent.com/draios/sysdig-cloud-scripts/master/agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
 	echo "* Downloading Sysdig daemonset slim v2 yaml"
 	curl -s -o $WORKDIR/sysdig-agent-slim-daemonset-v2.yaml https://raw.githubusercontent.com/draios/sysdig-cloud-scripts/master/agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
+	if [ $INSTALL_ANALYZER -eq 1 ]; then
+		echo "* Downloading Sysdig Image Analyzer config map yaml"
+		curl -H 'Cache-Control: no-cache' -s -o $WORKDIR/sysdig-image-analyzer-configmap.yaml https://raw.githubusercontent.com/draios/sysdig-cloud-scripts/master/agent_deploy/kubernetes/sysdig-image-analyzer-configmap.yaml
+		echo "* Downloading Sysdig Image Analyzer daemonset v1 yaml"
+		curl -H 'Cache-Control: no-cache' -s -o $WORKDIR/sysdig-image-analyzer-daemonset.yaml https://raw.githubusercontent.com/draios/sysdig-cloud-scripts/master/agent_deploy/kubernetes/sysdig-image-analyzer-daemonset.yaml
+    fi
 }
 
 function unsupported {
@@ -46,6 +52,7 @@ function help {
 	echo "                [-cp | --collector_port <value>] [-s | --secure <value>] [-cc | --check_certificate <value>] \ "
 	echo "                [-ns | --namespace | --project <value>] [-ac | --additional_conf <value>] \ "
 	echo "                [-op | --openshift] [-as | --agent_slim] [-av | --agent_version <value>] \ "
+	echo "                [-ia | --imageanalyzer ] [-am | --analysismanager <value>] [-ds | --dockersocket <value>] [-cs | --crisocket <value>] [-cv | --customvolume <value>] \ "
 	echo "                [-cn | --cluster_name <value>] [-r | --remove ] [-h | --help]"
 	echo ""
 	echo " -a  : secret access key, as shown in Sysdig Monitor"
@@ -60,6 +67,11 @@ function help {
 	echo " -av : if provided, use the agent-version specified. (default: latest)"
 	echo " -r  : if provided, will remove the sysdig agent's daemonset, configmap, clusterrolebinding,"
 	echo "       serviceacccount and secret from the specified namespace"
+	echo " -am : Analysis Manager endpoint for Sysdig Secure"
+	echo " -ds : docker socket for Image Analyzer"
+	echo " -cs : CRI socket for Image Analyzer"
+	echo " -cv : custom volume for Image Analyzer"
+	echo " -ia : if not provided, will skip Image Analyzer installation"
 	echo " -h  : print this usage and exit"
 	echo
 	exit 1
@@ -201,6 +213,26 @@ function install_k8s_agent {
 	echo "    new_k8s: true" >> $CONFIG_FILE
 	kubectl apply -f $CONFIG_FILE --namespace=$NAMESPACE
 
+	if [ $INSTALL_ANALYZER -eq 1 ]; then
+		# Image Analyzer config map
+		IA_CONFIG_FILE=$WORKDIR/sysdig-image-analyzer-configmap.yaml
+		
+		if [ ! -z "$ANALYSIS_MANAGER" ]; then
+			echo "* Setting Analysis Manager endpoint for Image Analyzer"
+			echo "  collector_endpoint: $ANALYSIS_MANAGER" >> $IA_CONFIG_FILE
+		fi
+		if [ ! -z "$DOCKER_SOCKET_PATH" ]; then
+			echo "* Setting docker socket path"
+			echo "  docker_socket_path: $DOCKER_SOCKET_PATH" >> $IA_CONFIG_FILE
+		fi
+		if [ ! -z "$CRI_SOCKET_PATH" ]; then
+			echo "* Setting CRI socket path"
+			echo "  cri_socket_path: $CRI_SOCKET_PATH" >> $IA_CONFIG_FILE
+		fi
+
+		kubectl apply -f $IA_CONFIG_FILE --namespace=$NAMESPACE
+    fi
+
 	AGENT_STRING="agent"
 	if [ ! -z "$AGENT_SLIM" ]; then
 		DAEMONSET_FILE="$WORKDIR/sysdig-agent-slim-daemonset-v2.yaml"
@@ -232,6 +264,33 @@ function install_k8s_agent {
 	echo -e "\nMake sure the above pods all turn to \"Running\" state before continuing"
 	echo "Should any pod not reach the \"Running\" state, further info can be obtained from logs as follows"
 	echo "'kubectl logs <agent-pod-name> -n $NAMESPACE' "
+
+	if [ $INSTALL_ANALYZER -eq 1 ]; then
+		# Deploy Image Analyzer
+		IA_FILE=$WORKDIR/sysdig-image-analyzer-daemonset.yaml
+		if [ ! -z "$IA_CUSTOM_PATH" ]; then
+			NL="\n"
+			if [[ $uname -eq "Darwin" ]]; then
+				NL=$'\\\n'
+			fi
+
+			IA_MATCH="Add custom volume here"
+			IA_INSERT_VOLUME="      - name: custom-volume${NL}        hostPath:${NL}          path: ${IA_CUSTOM_PATH}"
+			
+			sed -i.bak -e "s|${IA_MATCH}|${IA_MATCH}${NL}${IA_INSERT_VOLUME}|" $IA_FILE
+
+			IA_MATCH="Add custom volume mount here"
+			IA_INSERT_VOLUME="        - mountPath: ${IA_CUSTOM_PATH}${NL}          name: custom-volume"
+
+			sed -i.bak -e "s|${IA_MATCH}|${IA_MATCH}${NL}${IA_INSERT_VOLUME}|" $IA_FILE
+		fi
+
+		echo "* Deploying the Image Analyzer"
+		kubectl apply -f $IA_FILE --namespace=$NAMESPACE
+
+		echo -e "\nThe list of Image Analyzers pods deployed in the namespace \"$NAMESPACE\" are:"
+		kubectl get pods -n $NAMESPACE | grep "image-analyzer"
+	fi
 }
 
 function remove_agent {
@@ -244,6 +303,14 @@ function remove_agent {
 
 	echo "* Deleting the sysdig-agent configmap"
 	kubectl delete configmap sysdig-agent --namespace=$NAMESPACE
+
+	if [ "$(kubectl get pods -n $NAMESPACE | grep -c "image-analyzer")" -ge 1 ]; then 
+		echo "* Deleting the sysdig-image-analyzer daemonset"
+		kubectl delete daemonset sysdig-image-analyzer --namespace=$NAMESPACE
+
+		echo "* Deleting the sysdig-image-analyzer configmap"
+		kubectl delete configmap sysdig-image-analyzer --namespace=$NAMESPACE
+    fi
 
 	echo "* Deleting the sysdig-agent secret"
 	kubectl delete secret sysdig-agent --namespace=$NAMESPACE
@@ -278,6 +345,7 @@ fi
 NAMESPACE="sysdig-agent"
 REMOVE_AGENT=0
 OPENSHIFT=0
+INSTALL_ANALYZER=0
 AGENT_VERSION="latest"
 WORKDIR=""
 
@@ -377,6 +445,42 @@ do
 			fi
 			shift
 			;;
+		-am|--analysismanager)
+			if is_valid_value "${2}"; then
+				ANALYSIS_MANAGER="${2}"
+			else
+				echo "ERROR: no value provided for Analysis Manager option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
+		-ds|--dockersocket)
+			if is_valid_value "${2}"; then
+				DOCKER_SOCKET_PATH="${2}"
+			else
+				echo "ERROR: no value provided for docker socket path option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
+		-cs|--crisocket)
+			if is_valid_value "${2}"; then
+				CRI_SOCKET_PATH="${2}"
+			else
+				echo "ERROR: no value provided for CRI socket path option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
+		-cv|--customvolume)
+			if is_valid_value "${2}"; then
+				IA_CUSTOM_PATH="${2}"
+			else
+				echo "ERROR: no value provided for custom volume path option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
 		-as|--agent_slim)
 			AGENT_SLIM=1
 			;;
@@ -385,6 +489,9 @@ do
 			;;
 		-r|--remove)
 			REMOVE_AGENT=1
+			;;
+		-ia|--imageanalyzer)
+			INSTALL_ANALYZER=1
 			;;
 		-h|--help)
 			help
