[SMAGENT-3181] Update cluster install scripts to include necessary permissions for leases for OpenShift (#2720)
This commit adds the sysdig-agent cluster role from draios/sysdig-cloud-scripts@master/agent_deploy/kubernetes/sysdig-agent-clusterrole.yaml (raw) to OpenShift clusters and adds it to the sysdig-agent service account. The privileged SCC and cluster-reader role are still applied as well.

I tested the install script on Kubernetes as well as Openshift 4 by doing removal without install, install then remove, and back to back installs. I checked the logs to make sure that leases were being acquired as expected.

diff --git a/scripts/install-agent-kubernetes b/scripts/install-agent-kubernetes
--- a/scripts/install-agent-kubernetes
+++ b/scripts/install-agent-kubernetes
@@ -99,6 +99,15 @@ function is_valid_value {
 	fi
 }
 
+function already_exists {
+	if [[ ${1} =~ "AlreadyExists" || ${1} =~ "already exists" ]]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
+
 function create_namespace {
 	fail=0
 	if [ $OPENSHIFT -eq 0 ]; then
@@ -108,13 +117,13 @@ function create_namespace {
 		echo "* Creating project: $NAMESPACE"
 		out=$(oc adm new-project $NAMESPACE --node-selector='app=sysdig-agent' 2>&1) || { fail=1 && echo "oc adm new-project failed!"; }
 		# label all nodes
-		oc label node --all "app=sysdig-agent"
+		oc label --overwrite node --all "app=sysdig-agent"
 
 		# Set the project to the namespace
 		switch=$(oc project $NAMESPACE 2>&1)
 	fi
 	if [ $fail -eq 1 ]; then
-		if [[ "$out" =~ "AlreadyExists" || "$out" =~ "already exists" ]]; then
+		if already_exists "$out"; then
 			echo "$out. Continuing..."
 		else
 			echo "$out"
@@ -133,7 +142,7 @@ function create_sysdig_serviceaccount {
 		out=$(oc create serviceaccount sysdig-agent -n $NAMESPACE 2>&1) || { fail=1 && echo "oc create serviceaccount failed!"; }
 	fi
 	if [ $fail -eq 1 ]; then
-		if [[ "$out" =~ "AlreadyExists" || "$out" =~ "already exists" ]]; then
+		if already_exists "$out"; then
 			echo "$out. Continuing..."
 		else
 			echo "$out"
@@ -149,14 +158,19 @@ function install_k8s_agent {
 		kubectl apply -f $WORKDIR/sysdig-agent-clusterrole.yaml
 		outbinding=$(kubectl create clusterrolebinding sysdig-agent --clusterrole=sysdig-agent --serviceaccount=$NAMESPACE:sysdig-agent --namespace=$NAMESPACE 2>&1) || { fail=1 && echo "kubectl create clusterrolebinding failed!"; }
 	else
+		echo "* Creating sysdig-agent clusterrole"
+		oc apply -f $WORKDIR/sysdig-agent-clusterrole.yaml
 		echo "* Creating sysdig-agent access policies"
 		outbinding=$(oc adm policy add-scc-to-user privileged -n $NAMESPACE -z sysdig-agent 2>&1) || { fail=1 && echo "oc adm policy add-scc-to-user failed!"; }
-		if [ $fail -eq 0 ]; then
-			outbinding=$(oc adm policy add-cluster-role-to-user cluster-reader -n $NAMESPACE -z sysdig-agent 2>&1) || { fail=1 && echo "oc adm policy add-cluster-role-to-user failed!"; }
+		if [[ $fail -eq 0 ]] || already_exists "$outbinding"; then
+			outbinding=$(oc adm policy add-cluster-role-to-user cluster-reader -n $NAMESPACE -z sysdig-agent 2>&1) || { fail=1 && echo "oc adm policy add-cluster-role-to-user cluster-reader failed!"; }
+		fi
+		if [[ $fail -eq 0 ]] || already_exists "$outbinding"; then
+			outbinding=$(oc adm policy add-cluster-role-to-user sysdig-agent -n $NAMESPACE -z sysdig-agent 2>&1) || { fail=1 && echo "oc adm policy add-cluster-role-to-user sysdig-agent failed!"; }
 		fi
 	fi
 	if [ $fail -eq 1 ]; then
-		if [[ "$outbinding" =~ "AlreadyExists" || "$outbinding" =~ "already exists" ]]; then
+		if already_exists "$outbinding"; then
 			echo "$outbinding. Continuing..."
 		else
 			echo "$outbinding"
@@ -168,7 +182,7 @@ function install_k8s_agent {
 	fail=0
 	outsecret=$(kubectl create secret generic sysdig-agent --from-literal=access-key=$ACCESS_KEY --namespace=$NAMESPACE 2>&1) || { fail=1 && echo "kubectl create secret failed!"; }
 	if [ $fail -eq 1 ]; then
-		if [[ "$outsecret" =~ "AlreadyExists" || "$outsecret" =~ "already exists" ]]; then
+		if already_exists "$outsecret"; then
 			echo "$outsecret. Re-creating secret..."
 			kubectl delete secrets sysdig-agent --namespace=$NAMESPACE 2>&1
 			kubectl create secret generic sysdig-agent --from-literal=access-key=$ACCESS_KEY --namespace=$NAMESPACE 2>&1
@@ -443,8 +457,12 @@ function remove_agent {
 		kubectl delete clusterrole sysdig-agent
 	else
 		echo "* Removing cluster role and security constraints"
+		oc adm policy remove-cluster-role-from-user sysdig-agent -n $NAMESPACE -z sysdig-agent
 		oc adm policy remove-cluster-role-from-user cluster-reader -n $NAMESPACE -z sysdig-agent
 		oc adm policy remove-scc-from-user privileged -n $NAMESPACE -z sysdig-agent
+		
+		echo "* Deleting the sysdig-agent clusterrole"
+		oc delete clusterrole sysdig-agent
 
 		echo "* Deleting labels from oc nodes"
 		oc label node --all app-
