re-add NIA, add NA as seperate option.

diff --git a/scripts/install-agent-kubernetes b/scripts/install-agent-kubernetes
--- a/scripts/install-agent-kubernetes
+++ b/scripts/install-agent-kubernetes
@@ -54,7 +54,8 @@ function help {
 	echo "                [-cp | --collector_port <value>] [-s | --secure <value>] [-cc | --check_certificate <value>] \ "
 	echo "                [-ns | --namespace | --project <value>] [-ac | --additional_conf <value>] \ "
 	echo "                [-op | --openshift] [-as | --agent_slim] [-av | --agent_version <value>] \ "
-	echo "                [-na | --nodeanalyzer ] [-am | --analysismanager <value>] [-ds | --dockersocket <value>] [-cs | --crisocket <value>] [-cv | --customvolume <value>] \ "
+	echo "                [-se | --secure_endpoint <value> ] [-na | --nodeanalyzer ] \ "
+	echo "                [-ia | --imageanalyzer ] [-am | --analysismanager <value>] [-ds | --dockersocket <value>] [-cs | --crisocket <value>] [-cv | --customvolume <value>] \ "
 	echo "                [-cn | --cluster_name <value>] [-r | --remove ] [-h | --help]"
 	echo ""
 	echo " -a  : secret access key, as shown in Sysdig Monitor"
@@ -69,7 +70,9 @@ function help {
 	echo " -av : if provided, use the agent-version specified. (default: latest)"
 	echo " -r  : if provided, will remove the sysdig agent's daemonset, configmap, clusterrolebinding,"
 	echo "       serviceacccount and secret from the specified namespace"
-	echo " -na : if provided, will install the Node Analyzer"
+	echo " -se : if provided, will be used as the host in the Node Analyzer endpoints."
+	echo " -na : if provided, will install the Node Analyzer. It is an error to set both -ia and -na."
+	echo " -ia : if provided, will install the Node Image Analyzer. It is an error to set both -ia and -na."
 	echo " -am : Analysis Manager endpoint for Sysdig Secure"
 	echo " -ds : docker socket for Image Analyzer"
 	echo " -cs : CRI socket for Image Analyzer"
@@ -146,7 +149,7 @@ function install_k8s_agent {
 		fi
 	fi
 	if [ $fail -eq 1 ]; then
-		if [[ "$outbinding" =~ "AlreadyExists" ]]; then
+		if [[ "$out" =~ "AlreadyExists" || "$out" =~ "already exists" ]]; then
 			echo "$outbinding. Continuing..."
 		else
 			echo "$outbinding"
@@ -158,7 +161,7 @@ function install_k8s_agent {
 	fail=0
 	outsecret=$(kubectl create secret generic sysdig-agent --from-literal=access-key=$ACCESS_KEY --namespace=$NAMESPACE 2>&1) || { fail=1 && echo "kubectl create secret failed!"; }
 	if [ $fail -eq 1 ]; then
-		if [[ "$outsecret" =~ "AlreadyExists" ]]; then
+		if [[ "$outsecret" =~ "AlreadyExists" || "$outsecret" =~ "already exists" ]]; then
 			echo "$outsecret. Re-creating secret..."
 			kubectl delete secrets sysdig-agent --namespace=$NAMESPACE 2>&1
 			kubectl create secret generic sysdig-agent --from-literal=access-key=$ACCESS_KEY --namespace=$NAMESPACE 2>&1
@@ -216,13 +219,16 @@ function install_k8s_agent {
 	echo "    new_k8s: true" >> $CONFIG_FILE
 	kubectl apply -f $CONFIG_FILE --namespace=$NAMESPACE
 
-	if [ $INSTALL_ANALYZER -eq 1 ]; then
+	if [ $INSTALL_IMAGE_ANALYZER -eq 1 ] || [ $INSTALL_NODE_ANALYZER -eq 1 ]; then
 		# Image Analyzer config map
 		IA_CONFIG_FILE=$WORKDIR/sysdig-image-analyzer-configmap.yaml
 		
 		# If the collector was changed but the analysis manager was not this was
 		# most likely an onprem install, add the default analysis manager for that onprem
-		if [ ! -z "$COLLECTOR" ] && [ -z "$ANALYSIS_MANAGER" ]; then
+		if [ ! -z "$SECURE_ENDPOINT" ] && [ -z "$ANALYSIS_MANAGER" ]; then
+		  ANALYSIS_MANAGER="https://${SECURE_ENDPOINT}/internal/scanning/scanning-analysis-collector"
+			echo "* Configuring Analysis Manager endpoint to ${ANALYSIS_MANAGER}. You can also use the -am option to explicitly specify it."
+		elif [ ! -z "$COLLECTOR" ] && [ -z "$ANALYSIS_MANAGER" ]; then
 			ANALYSIS_MANAGER="https://${COLLECTOR}/internal/scanning/scanning-analysis-collector"
 			echo "* Configuring Analysis Manager endpoint to ${ANALYSIS_MANAGER}. You can also use the -am option to explicitly specify it."
 		fi
@@ -251,14 +257,20 @@ function install_k8s_agent {
 		fi
 
 		kubectl apply -f $IA_CONFIG_FILE --namespace=$NAMESPACE
+	fi
 
+  if [ $INSTALL_NODE_ANALYZER -eq 1 ]; then
 		# Benchmark Runner config map
 		BR_CONFIG_FILE=$WORKDIR/sysdig-benchmark-runner-configmap.yaml
 
-		if [ ! -z "$COLLECTOR" ]; then
+		if [ ! -z "$SECURE_ENDPOINT" ]; then
+			echo "* Setting Secure endpoint for Benchmark Runner"
+			echo "  collector_endpoint: https://$SECURE_ENDPOINT" >> $BR_CONFIG_FILE
+		elif [ ! -z "$COLLECTOR" ]; then
 			echo "* Setting Collector endpoint for Benchmark Runner"
 			echo "  collector_endpoint: https://$COLLECTOR" >> $BR_CONFIG_FILE
 		fi
+
 		if [ ! -z "$CHECK_CERT" ]; then
 			echo "* Setting SSL certificate check level"
 			echo "  ssl_verify_certificate: \"$CHECK_CERT\"" >> $BR_CONFIG_FILE
@@ -301,7 +313,32 @@ function install_k8s_agent {
 	echo "Should any pod not reach the \"Running\" state, further info can be obtained from logs as follows"
 	echo "'kubectl logs <agent-pod-name> -n $NAMESPACE' "
 
-	if [ $INSTALL_ANALYZER -eq 1 ]; then
+	if [ $INSTALL_IMAGE_ANALYZER -eq 1 ]; then
+		# Deploy Image Analyzer
+		IA_FILE=$WORKDIR/sysdig-image-analyzer-daemonset.yaml
+		if [ ! -z "$IA_CUSTOM_PATH" ]; then
+			NL="\n"
+			if [[ $uname -eq "Darwin" ]]; then
+				NL=$'\\\n'
+			fi
+
+			IA_MATCH="Add custom volume here"
+			IA_INSERT_VOLUME="      - name: custom-volume${NL}        hostPath:${NL}          path: ${IA_CUSTOM_PATH}"
+
+			sed -i.bak -e "s|${IA_MATCH}|${IA_MATCH}${NL}${IA_INSERT_VOLUME}|" $IA_FILE
+
+			IA_MATCH="Add custom volume mount here"
+			IA_INSERT_VOLUME="        - mountPath: ${IA_CUSTOM_PATH}${NL}          name: custom-volume"
+
+			sed -i.bak -e "s|${IA_MATCH}|${IA_MATCH}${NL}${IA_INSERT_VOLUME}|" $IA_FILE
+		fi
+
+		echo "* Deploying the Image Analyzer"
+		kubectl apply -f $IA_FILE --namespace=$NAMESPACE
+
+		echo -e "\nThe list of Image Analyzers pods deployed in the namespace \"$NAMESPACE\" are:"
+		kubectl get pods -n $NAMESPACE | grep "image-analyzer"
+	elif [ $INSTALL_NODE_ANALYZER -eq 1 ]; then
 		# Deploy Image Analyzer
 		NA_FILE=$WORKDIR/sysdig-node-analyzer-daemonset.yaml
 		if [ ! -z "$NA_CUSTOM_PATH" ]; then
@@ -340,7 +377,14 @@ function remove_agent {
 	echo "* Deleting the sysdig-agent configmap"
 	kubectl delete configmap sysdig-agent --namespace=$NAMESPACE
 
-	if [ "$(kubectl get pods -n $NAMESPACE | grep -c "node-analyzer")" -ge 1 ]; then
+
+	if [ "$(kubectl get pods -n $NAMESPACE | grep -c "image-analyzer")" -ge 1 ]; then
+	  echo "* Deleting the sysdig-image-analyzer daemonset"
+		kubectl delete daemonset sysdig-image-analyzer --namespace=$NAMESPACE
+
+		echo "* Deleting the sysdig-image-analyzer configmap"
+		kubectl delete configmap sysdig-image-analyzer --namespace=$NAMESPACE
+	elif [ "$(kubectl get pods -n $NAMESPACE | grep -c "node-analyzer")" -ge 1 ]; then
 		echo "* Deleting the sysdig-node-analyzer daemonset"
 		kubectl delete daemonset sysdig-node-analyzer --namespace=$NAMESPACE
 
@@ -529,6 +573,15 @@ do
 			fi
 			shift
 			;;
+		-se|--secure_endpoint)
+			if is_valid_value "${2}"; then
+				SECURE_ENDPOINT="${2}"
+			else
+				echo "ERROR: no value provided for Secure endpoint option, use -h | --help for $(basename ${0}) Usage"
+				exit 1
+			fi
+			shift
+			;;
 		-as|--agent_slim)
 			AGENT_SLIM=1
 			;;
@@ -538,8 +591,11 @@ do
 		-r|--remove)
 			REMOVE_AGENT=1
 			;;
+		-ia|--imageanalyzer)
+			INSTALL_IMAGE_ANALYZER=1
+			;;
 		-na|--nodeanalyzer)
-			INSTALL_ANALYZER=1
+			INSTALL_NODE_ANALYZER=1
 			;;
 		-h|--help)
 			help
@@ -565,6 +621,11 @@ fi
 
 if [ -z $COLLECTOR ]; then
 	echo "No collector argument provided. Using default value: collector.sysdigcloud.com"
+fi
+
+if [ $INSTALL_IMAGE_ANALYZER -eq 1 ] && [ $INSTALL_NODE_ANALYZER -eq 1 ]; then
+  echo "ERROR: The Node Analyzer and Node Image Analyzer cannot both be installed. use -h | --help for $(basename ${0}) Usage"
+  exit 1
 fi
 
 echo "* Detecting operating system"
