Error out early if we are unable to rmmod probe modules

diff --git a/scripts/quick-build-and-test b/scripts/quick-build-and-test
--- a/scripts/quick-build-and-test
+++ b/scripts/quick-build-and-test
@@ -6,6 +6,11 @@ MODE=$1
 
 rmmod sysdig-probe || true
 rmmod sysdigcloud-probe || true
+ACTIVE_MODS=$(lsmod | grep -c "sysdig.*_probe" || true)
+if [ ${ACTIVE_MODS} -gt 0 ]; then
+	echo "Unable to rmmod existing probe modules"
+	exit 1
+fi
 rm -rf agent/build || true
 rm -rf sysdig/build || true
 agent/bootstrap-agent
