More options in the precompiled script

diff --git a/scripts/sysdig-probe-installer b/scripts/sysdig-probe-installer
--- a/scripts/sysdig-probe-installer
+++ b/scripts/sysdig-probe-installer
@@ -13,8 +13,8 @@ if ! hash lsmod > /dev/null 2>&1; then
 	exit 1
 fi
 
-if ! hash wget > /dev/null 2>&1; then
-	echo "This program requires wget"
+if ! hash curl > /dev/null 2>&1; then
+	echo "This program requires curl"
 	exit 1
 fi
 
@@ -31,6 +31,9 @@ fi
 ARCH=$(uname -m)
 KERNEL_RELEASE=$(uname -r)
 SYSDIG_VERSION=$(sysdig --version | cut -d' ' -f3)
+REPOSITORY="cgroups"
+
+echo "Finding kernel config for $KERNEL_RELEASE"
 
 if [ -f /proc/config.gz ]; then
 	echo "Found kernel config at /proc/config.gz"
@@ -38,6 +41,14 @@ if [ -f /proc/config.gz ]; then
 elif [ -f /boot/config-$KERNEL_RELEASE ]; then
 	echo "Found kernel config at /boot/config-$KERNEL_RELEASE"
 	HASH=$(md5sum /boot/config-$KERNEL_RELEASE | cut -d' ' -f1)	
+elif [ ! -z "$SYSDIG_HOST_ROOT" ] && [ -f $SYSDIG_HOST_ROOT/boot/config-$KERNEL_RELEASE ]; then
+	echo "Found kernel config at $SYSDIG_HOST_ROOT/boot/config-$KERNEL_RELEASE"
+	HASH=$(md5sum $SYSDIG_HOST_ROOT/boot/config-$KERNEL_RELEASE | cut -d' ' -f1)	
+fi
+
+if [ -z "$HASH" ]; then
+	echo "Cannot find kernel config"
+	exit 1
 fi
 
 SYSDIG_PROBE_FILENAME="sysdig-probe-$SYSDIG_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko"
@@ -48,11 +59,14 @@ if [ -f ~/.sysdig/$SYSDIG_PROBE_FILENAME ]; then
 	exit $?
 fi
 
-URL="https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/$SYSDIG_PROBE_FILENAME"
+URL="https://s3.amazonaws.com/download.draios.com/$REPOSITORY/sysdig-probe-binaries/$SYSDIG_PROBE_FILENAME"
 
 echo "Trying to download precompiled module from $URL"
-if curl --create-dirs -o ~/.sysdig/ $URL; then
+if curl --create-dirs -f -s -o ~/.sysdig/$SYSDIG_PROBE_FILENAME $URL; then
 	echo "Download succeeded, loading module"
 	insmod ~/.sysdig/$SYSDIG_PROBE_FILENAME
 	exit $?
+else
+	echo "Download failed, consider compiling your own kernel module or getting in touch with the sysdig community"
+	exit 1
 fi
