[SMAGENT-1540] agent build presubmit (#1351)
[SMAGENT-1540] Create the scripts for Jenkins to run the presubmit build and run the system tests. This is associated with the agent-build-presubmit job.

diff --git a/scripts/jenkins/run-tests b/scripts/jenkins/run-tests
--- a/scripts/jenkins/run-tests
+++ b/scripts/jenkins/run-tests
@@ -22,6 +22,17 @@ rm -f $TESTS_LOG
 
 if [ -n "$FAILED_TESTS" ]
 then
-	echo "Some tests failed, restarting"
-	unshare -m /bin/bash -c "$SETUP_CMD && cd /opt/draios/test && ./tests --gtest_filter=$FAILED_TESTS"
+	echo "Some tests failed... restarting"
+	TESTS_LOG=`mktemp /tmp/tests.log.XXXXXX`
+	unshare -m /bin/bash -c "$SETUP_CMD && cd /opt/draios/test && ./tests --gtest_filter=$FAILED_TESTS" 2>&1 | tee $TESTS_LOG
+	FAILED_TESTS=$(awk '/ FAILED / && test_list==1 { print $4 } / FAILED.*listed below:/ { test_list=1 }' < $TESTS_LOG | tr \\n :)
+	rm -f $TESTS_LOG
+
+	if [ -n "$FAILED_TESTS" ]
+	then
+		echo "Tests failed again, returning failure"
+		exit 1
+	fi
 fi
+
+exit 0
